### ISSUE TITLE
Prepare theme for M3.9,M3.10 and M3.11 release

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-theme_squared#8]
Hi @gjb2048 

could you prepare the theme for release for the mentioned versions?

Thank you!

**Comment by gjb2048** [comment]
@dasistwas Will do.

**Comment by gjb2048** [comment]
@dasistwas The two things I've found with the 'master' for M3.9 in M3.10 are a bit of cosmetic issues with the navbar and the notifications, and more critically, the 'navbarsearch' setting does not work when standard or global course search.  This I can deal with as is all down to the fact that 'search_box()' has changed.  I've recently been in the same area with the Adaptable theme, so can fix this.  But with Adaptable, I have it so that if global search is disabled, then course search applies otherwise.  So, would you want the setting to change such that if global search was enabled then that is used (as there is a new course search option on its form) otherwise fall back to 'course search', thus go from three to two options, being either Moodle's search offering or Squared's?

I've not looked at M3.11 yet, but will look at any current changes.

Please let me know how you want me to solve this.

**Comment by gjb2048** [comment]
Notes to self:

- M3.10 is BS4.5.0 and M3.11 is BS4.6.0.
- Embedded layout now has provision for fake blocks via 'side_pre' in M3.11.
- blocks_for_region() and blocks() has changed in M3.11 for fake blocks.  Thus this is an API change that definitely means a separate branch to support M3.11.

**Comment by gjb2048** [comment]
@dasistwas I've been fixing things that I'm spotting in M3.9 that I also see that affect M3.10, so the cog menu on the navbar menu item logo colour and the header logo / background image not working on small devices correctly.  Have you spotted anything please?

**Comment by gjb2048** [comment]
@dasistwas Any news on what you'd like me to do for the search (https://github.com/Wunderbyte-GmbH/moodle-theme_squared/issues/8#issuecomment-835421049) please?  Have you spotted anything else?

**Comment by dasistwas** [comment]
The M3.10 version is now productive on www.virtuelle-ph.at. I will open separate issues for problems.
